### ISSUE TITLE
Import basic CSS by default

### ISSUE THREAD

**Issue by jameskolce** [KolceLabs/Delta#1]
```css
@custom-media --extra-small (width < 480px);
@custom-media --small (width >= 480px);
@custom-media --medium (width >= 768px);
@custom-media --large (width >= 960px);
@custom-media --extra-large (width >= 1100px);
@custom-media --only-small (480px < width <= 768px);
@custom-media --only-medium (768px < width <= 960px);
@custom-media --only-large (960px < width <= 1100px);

:root {
  /* Font size for small devices */
  --font-size: 16px;

  /* Font size for large devices */
  --font-size-large: 18px;

  /* Space between characters */
  --tracking: 0.05em;

  /* Type scale ratio */
  --type-ratio: 1.2;

  /* Font families */
  --font-primary: "Helvetica", "Arial", sans-serif;
  --font-secondary: "Helvetica", "Arial", sans-serif;
  --font-mono: "Consolas", monospace;
  --font-print-primary: "Georgia", "Times New Roman", "Times", serif;
  --font-print-secondary: "Georgia", "Times New Roman", "Times", serif;

  /* Transitions */
  --transition-duration: 150ms;

  /* Spacing */
  --spacing-xs: 0.5lh;
  --spacing-s: 1lh;
  --spacing-m: 2lh;
  --spacing-l: 3lh;
  --spacing-xl: 4lh;

  /* Color palette */
  --color-base-primary: #C65146;
  --color-base-selection: #EBE1D3;
  --color-base-lines: #DCDCDC;

  --color-text-primary: #444444;
  --color-text-secondary: #777777;
  --color-text-heading: #222222;
  --color-text-inverted: white;

  --color-background-dark: #32373d;
  --color-background-light: #f5f5f5;
  --color-background-body: white;
}

*,
::before,
::after {
  box-sizing: inherit;
}

:root {
  box-sizing: border-box;
  font-family: --font-primary;
  line-height: 1.5;
  background-color: --color-background-body;
  color: --color-text-primary;
  font-size: --font-size;
  font-size: --font-size-large ?if media (--small);
  text-rendering: optimizeLegibility;
}
```
